### ISSUE TITLE
notebooks_and_code\\additional_code folder 

### ISSUE THREAD

**Issue by etemadism** [AlexanderKroll/KM_prediction_function#2]
Hi 
I could not find this folder in the code or data folder: notebooks_and_code\\additional_code. Is this available? 
Thanks

**Comment by AlexanderKroll** [comment]
Dear etemadism,

If I remember correctly, you don't need the content of the "additional_code" folder for this repository. But if you still want to access it, you can get it here: https://github.com/AlexanderKroll/KM_prediction/tree/master/notebooks_and_code/additional_code
